# Generated by Django 5.1.4 on 2025-01-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="execution_time",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Время выполнения (в секундах)"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Периодичность в днях"
            ),
        ),
    ]
